# Generated by Django 3.2.8 on 2021-10-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TFinances',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('desc_type', models.CharField(blank=True, max_length=155, null=True)),
                ('date_hour', models.DateTimeField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('card', models.CharField(blank=True, max_length=12, null=True)),
                ('store_owner', models.CharField(blank=True, max_length=14, null=True)),
                ('store', models.CharField(blank=True, max_length=19, null=True)),
            ],
            options={
                'db_table': 't_finances',
                'managed': True,
            },
        ),
    ]
