# Generated by Django 3.2.8 on 2021-10-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finances',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='finances',
            table='t_finances',
        ),
    ]
